language: node_js

node_js:
    - "10"
    
services:
    - docker

stages: 
    - name: test
    - name: build and push
      if: (branch = master) AND (type = push) AND (repo = Victor-H5/react-webpack)

jobs: 
    include:
        - stage: test
          name: 'unit test'
          script: 
            - npm run test

        - stage: build and push
          script: 
            - npm run build
          deploy: 
            provider: pages
            skip_cleanup: true
            github_token: $GITHUB_TOKEN
            local_dir: dist
            repo: $TRAVIS_REPO_SLUG
            target_branch: gh-pages
            on:
                branch: master

notifications: 
    email:
        recipients: 
            - leon.wei@tradeshift.com
        on_success: change
        on_failure: always
